### ISSUE TITLE
Icons don't support filling color

### ISSUE THREAD

**Issue by driesvints** [skydiver/blade-icons-remix#5]
Hi there,

I'm opening this issue because we're currently working on integrating an icon search into the upcoming blade-ui-kit.com website. For this we need to be able to control the look and feel of the icons, especially its color.

It seems that this icon set doesn't supports filling its color yet. For this reason we've currently excluded your icon set from the search. It would be cool if you could fix this so your icon set can also be included in the global search.

### Details

[Here's an example](https://github.com/skydiver/blade-icons-remix/blob/master/resources/svg/24-hours-fill.svg?short_path=78875e3#L1) of your icon missing either `fill="none"  stroke="currentColor"` (outline icons) or `fill="currentColor"` (solid icons). 

### How to fix

Apply `fill="none"  stroke="currentColor"` to any outline icons ([Heroicons example](https://github.com/blade-ui-kit/blade-heroicons/blob/main/resources/svg/o-academic-cap.svg?short_path=c23120b#L1)) or `fill="currentColor"` to any solid icons ([Heroicons example](https://github.com/blade-ui-kit/blade-heroicons/blob/main/resources/svg/s-calculator.svg?short_path=7ad0b7e#L1)).

Also make sure you remove any attributes that don't belong on the icons like `id`, `class`, `width` & `height`, etc.

Please respond to this issue as soon as you've been able to fix this and tag a release and we'll include your library in the search.

**Comment by skydiver** [comment]
sorry @driesvints i missed this one ...
so, i should add the required property to every svg right?

how can i test it's working? adding font color to the parent container is enough?

**Comment by driesvints** [comment]
You can test by pasting the svg surrounded with a tailwind styles element:

```
<span class="text-red-500">
    <your svg here>
</span>
```

If the SVG shows with the red color you're good.

**Comment by skydiver** [comment]
@driesvints i've changed the svg files as you suggested; solid ones works fine, i have an issue with the outlines:

![image](https://user-images.githubusercontent.com/578784/93636444-5439b700-f9ca-11ea-9b45-d5ef77c5a0fb.png)
![image](https://user-images.githubusercontent.com/578784/93636450-5865d480-f9ca-11ea-9a6b-f08fc4297eb6.png)

will try to remove that strange border on the blue ones

fyi: this was my test components and [here is the PR](https://github.com/skydiver/blade-icons-remix/pull/7):
```
<span class="text-red-500">
    <x-ri-auction-fill class="w-20 h-20 m-8"/>
</span>

<span class="text-blue-500">
    <x-ri-auction-line class="w-20 h-20 m-8"/>
</span>

<span class="text-red-500">
    <x-ri-netflix-fill class="w-20 h-20 m-8"/>
</span>

<span class="text-blue-500">
    <x-ri-netflix-line class="w-20 h-20 m-8"/>
</span>
```

**Comment by skydiver** [comment]
ok @driesvints, version 1.3.0 add those attributes to svgs and enables fill color
let me know if there is anything else to do

**Comment by driesvints** [comment]
@skydiver sorry, haven't gotten to this yet. I'll try to check in on this soon. Thanks for the fix!

**Comment by driesvints** [comment]
The Remix icons are now added to the icon search on the site: https://blade-ui-kit.com/blade-icons
